# Generated by Django 5.2.6 on 2025-09-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mistake_note', '0002_remove_question_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-09-17 14:00:00'),
            preserve_default=False,
        ),
    ]
