# Generated by Django 5.2.6 on 2025-09-17 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mistake_note', '0003_question_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='문제에 대한 해설을 입력하세요.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.TextField(blank=True, help_text='객관식/복수 정답 보기를 콤마(,)로 구분하여 입력하세요.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('SA', 'Short Answer'), ('MA', 'Multiple Answer')], default='MCQ', max_length=3),
        ),
        migrations.AddField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mistake_note.exam'),
        ),
    ]
