# Generated by Django 5.2.6 on 2025-09-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mistake_note', '0004_exam_question_explanation_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, help_text='문제 관련 이미지를 업로드하세요.', null=True, upload_to='questions/'),
        ),
    ]
