# Generated by Django 5.2.6 on 2025-09-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mistake_note', '0006_remove_question_title_question_passage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(verbose_name='문제 내용'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, null=True, verbose_name='해설'),
        ),
        migrations.AlterField(
            model_name='question',
            name='passage',
            field=models.TextField(blank=True, null=True, verbose_name='지문'),
        ),
    ]
