# Generated by Django 5.2.6 on 2025-09-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mistake_note', '0007_alter_question_content_alter_question_explanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='incorrect_count',
            field=models.IntegerField(default=0, verbose_name='오답 횟수'),
        ),
        migrations.AddField(
            model_name='question',
            name='solved_count',
            field=models.IntegerField(default=0, verbose_name='풀이 횟수'),
        ),
    ]
