# Generated by Django 5.2.6 on 2025-09-20 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mistake_note', '0008_question_incorrect_count_question_solved_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='quiz_mode',
            field=models.BooleanField(default=True),
        ),
    ]
