# Generated by Django 5.2.6 on 2025-09-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mistake_note', '0009_useranswer_quiz_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_count',
            field=models.IntegerField(default=0, verbose_name='맞춘 횟수'),
        ),
    ]
